# -*- coding: utf-8 -*-
"""Untitled19.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wh0ftkuKarJRZMWaJZm-MOud97o4ds2K

Problem 1: Check if a Number is Prime
"""

def is_prime(n):
    if n < 2:
        return False
    for i in range(2, int(n ** 0.5) + 1):
        if n % i == 0:
            return False
    return True


print("Is 7 prime?", is_prime(7))

"""Problem 2: Reverse a String"""

def reverse_string(s):
    return s[::-1]


print("Reverse of 'hello':", reverse_string("hello"))

"""Problem 3: Calculate Factorial"""

def factorial(n):
    if n == 0:
        return 1
    return n * factorial(n - 1)


print("Factorial of 5:", factorial(5))

"""Problem 4: Sum of Digits"""

def sum_of_digits(n):
    return sum(int(d) for d in str(n))

print("Sum of digits in 1234:", sum_of_digits(1234))